apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clodflare-tunnel-credentials-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-sm-cluster-secret-store
    kind: SecretStore
  target:
    name: cloudflare-credentials
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: clodflare-tunnel-credentials
        property: ""
