apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clodflare-tunnel-credentials-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secretstore
    kind: SecretStore
  target:
    name: cloudflare-credentials
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: clodflare-tunnel-credentials
        property: ""
