apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: default-istio-operator
spec:
  meshConfig:
    enableTracing: true
    extensionProviders:
      - name: otel-tracing
        opentelemetry:
          port: {{ .Values.opentelemetry.port }}
          address: {{ .Values.opentelemetry.address }}
          service:
          resource_detectors:
            environment: {}