apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
spec:
  meshConfig:
    enableTracing: true

    defaultConfig:
      tracing:
        sampling: 100.0

    extensionProviders:
      - name: otel-tracing
        opentelemetry:
          service: {{ .Values.opentelemetry.address }}
          port: {{ .Values.opentelemetry.port }}
          http:
            path: /v1/traces
            timeout: 10s
            headers:
              content-type: application/json

    # Tell Istio to actually use the provider
    defaultProviders:
      tracing:
        - otel-tracing
