{{ range .Values.clusterIssuers }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .privateKeySecretRefName }}
spec:
  acme:
    email: {{ .email }}
    server: {{ .server }}
    privateKeySecretRef:
      name: {{ .privateKeySecretRefName }}
    solvers:
      - http01:
          ingress:
            class: {{ .solversIngressClass }}
{{ end }}
