apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-dns01-cloudflare-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-sm-cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: api-token
      remoteRef:
        key: cert-manager-dns01-cloudflare-token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
  target:
    name: cert-manager-dns01-cloudflare-secret
    creationPolicy: Owner
