name: infra-network
description: Network infrastructure setup for homelab
version: 0.1.0
apiVersion: v2
type: application
appVersion: "1.0.0"
maintainers:
  - name: KarafrOrg
    email: karafra@karafra.net
keywords:
  - networking
  - cert-manager
  - homelab
dependencies:
  - name: kiali-operator
    version: 2.20.0
    repository: https://kiali.org/helm-charts