name: infra-network
description: Network infrastructure setup for homelab
version: 0.1.0
apiVersion: v2
type: application
appVersion: "1.0.0"
maintainers:
  - name: KarafrOrg
    email: karafra@karafra.net
keywords:
  - networking
  - cert-manager
  - homelab
dependencies:
  - name: base
    version: 1.28.2
    alias: istio-base
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.28.2
    repository: https://istio-release.storage.googleapis.com/charts
  - name: cni
    version: 1.28.2
    repository: https://istio-release.storage.googleapis.com/charts
  - name: ztunnel
    version: 1.28.2
    repository: https://istio-release.storage.googleapis.com/charts
