apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  auth:
    strategy: anonymous
  deployment:
    cluster_wide_access: true
    view_only_mode: false
  external_services:
    prometheus:
      url: http://prometheus-operated.infra-monitoring.svc.cluster.local:9090
    grafana:
      enabled: true
      internal_url: 'https://grafana.infra-monitoring.svc.cluster.local:80/'
      external_url: 'https://grafana.karafra.net/'
      datasource_uid: "prometheus"
      dashboards:
        - name: "Istio Service Dashboard"
          variables:
            datasource: "var-datasource"
            namespace: "var-namespace"
            service: "var-service"
        - name: "Istio Workload Dashboard"
          variables:
            namespace: "var-namespace"
            workload: "var-workload"
            datasource: "var-datasource"
        - name: "Istio Mesh Dashboard"
        - name: "Istio Control Plane Dashboard"
        - name: "Istio Performance Dashboard"
  server:
    web_root: "/"